### ISSUE TITLE
LayoutBuilder does not support returning intrinsic dimensions on AlertDialog

### ISSUE THREAD

**Issue by zgramming** [theyakka/qr.flutter#102]
**Describe the bug**
When you click button to open dialog using `showDialog` and place **QrImage** on  alertDialog content  it will showing error `LayoutBuilder does not support returning intrinsic dimensions.`

### Reproduce code 
```dart
class DialogQR extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      title: Text(
        'QR-KU',
        style: appTheme.headline6(context).copyWith(fontWeight: FontWeight.bold),
      ),
      content: QrImage(
        errorStateBuilder: (context, error) =>
            Text(error.toString(), style: appTheme.caption(context)),
        data: 'disini nanti ID usernya/ emailnya',
        size: 100,
        // size: sizes.height(context) / 4,
      ),
    );
  }
}
```

**Screenshots**

### Using Qr Image
![with qr flutter](https://user-images.githubusercontent.com/38829404/88052782-fa14a500-cb84-11ea-892a-6f84e676e999.gif)

### Without Qr Image
<img width="204" alt="without qr flutter" src="https://user-images.githubusercontent.com/38829404/88052915-30522480-cb85-11ea-931a-9865cbd37cf7.PNG">

**Smartphone (please complete the following information):**
 - Device: [Google Pixel 2]
 - OS: [Android]

### Update

![with qr flutter(success)](https://user-images.githubusercontent.com/38829404/88053854-ac993780-cb86-11ea-8040-00137b2493df.gif)

After testing using real device (**Redmi Note 4**)  , but strangely it's work. Because this , i trying another emulator (**Google Pixel 3A**) and error showing again. 
It's only happen in emulator.

**Comment by brandon9405** [comment]
I solve this with a container widget given the static height and width

AlertDialog(
            insetPadding: EdgeInsets.symmetric(horizontal: 20),
            content: SingleChildScrollView(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: <Widget>[
                  Container(
                    child: Text(
                      'Scan this QR',
                      style: TextStyle(fontWeight: FontWeight.bold, fontSize: 20),
                    ),
                  ),
                  SizedBox(height: 15.0),
                  Container(
                    width: 200.0,
                    height: 200.0,
                    child: QrImage(
                      errorStateBuilder: (context, error) =>
                          Text(error.toString()),
                      data: "some data",
                    ),
                  ),
                ],
              ),
            ),
          );

**Comment by oom-** [comment]
Yes adding a container above did the trick for me:
```dart
Container(width: 280, height: 280, 
   child: QrImage(data: qrcodedata, version: QrVersions.auto, size: 310)
)
```

**Comment by abcd498936590** [comment]
> 我给定了静态高度和宽度，使用容器小部件解决了这个问题
> 
> AlertDialog（
> insetPadding：EdgeInsets.symmetric（horizo​​ntal：20），
> 内容：SingleChildScrollView（
> child：Column（
> mainAxisAlignment：MainAxisAlignment.center， child：
> [
> Container（
> child：Text（
> 'Scan this QR'，
> style：TextStyle（fontWeight：FontWeight。粗体，fontSize：20），
> ），
> ），
> SizedBox（高度：15.0），
> Container（
> 宽度：200.0，
> 高度：200.0，
> 子代：QrImage（
> errorStateBuilder：（context，error）=>
> Text（error.toString（）），
> 数据：“一些数据”，
> ），
> ），
> ]，
> ），
> ），
> ））；

Your answer is perfect.

I solved this problem through your answer, very good

**Comment by abcd498936590** [comment]
> I solve this with a container widget given the static height and width
> 
> AlertDialog(
> insetPadding: EdgeInsets.symmetric(horizontal: 20),
> content: SingleChildScrollView(
> child: Column(
> mainAxisAlignment: MainAxisAlignment.center,
> children: [
> Container(
> child: Text(
> 'Scan this QR',
> style: TextStyle(fontWeight: FontWeight.bold, fontSize: 20),
> ),
> ),
> SizedBox(height: 15.0),
> Container(
> width: 200.0,
> height: 200.0,
> child: QrImage(
> errorStateBuilder: (context, error) =>
> Text(error.toString()),
> data: "some data",
> ),
> ),
> ],
> ),
> ),
> );

Your answer is perfect.

I solved this problem through your answer, very good

**Comment by Angeloem** [comment]
But why does it happen in an emulator only?

**Comment by umitmutlurize** [comment]
> I solve this with a container widget given the static height and width
> 
> ```dart
> AlertDialog(
>   insetPadding: EdgeInsets.symmetric(horizontal: 20),
>   content: SingleChildScrollView(
>     child: Column(
>       mainAxisAlignment: MainAxisAlignment.center,
>       children: <Widget>[
>         Container(
>           child: Text(
>             'Scan this QR',
>             style: TextStyle(fontWeight: FontWeight.bold, fontSize: 20),
>           ),
>         ),
>         SizedBox(height: 15.0),
>         Container(
>           width: 200.0,
>           height: 200.0,
>           child: QrImage(
>             errorStateBuilder: (context, error) =>
>                 Text(error.toString()),
>             data: "some data",
>           ),
>         ),
>       ],
>     ),
>   ),
> );
> ```

that can't be responsive you can write MediaQuerry.of(context).size.width/5 ... whatever you competible with you

**Comment by lukef** [comment]
Seems like this is resolved. The QR code always works best when you add your own constraints.

**Comment by maganap** [comment]
For those interested in neither hardcoding a value, nor depending in a selected-by-you fraction of the MediaQuery:

Notice that in the [AlertDialog documentation](https://api.flutter.dev/flutter/material/AlertDialog-class.html) you can read:

> However, be aware that since [AlertDialog](https://api.flutter.dev/flutter/material/AlertDialog-class.html) tries to size itself using the intrinsic dimensions of its children, widgets such as [ListView](https://api.flutter.dev/flutter/widgets/ListView-class.html), [GridView](https://api.flutter.dev/flutter/widgets/GridView-class.html), and [CustomScrollView](https://api.flutter.dev/flutter/widgets/CustomScrollView-class.html), which use lazy viewports, will not work. If this is a problem, consider using [Dialog](https://api.flutter.dev/flutter/material/Dialog-class.html) directly.

So, you can use a `Dialog` instead if you want the QR to expand as much as the Dialog allows. You can actually enter into the `AlertDialog` definition and copy a couple of handlings from there (find the `title`, `content` and `actions`, and add some padding).

**Comment by anasfik** [comment]
I faced this problem also.
What are the possible ways that occur the problem to happen only on android emulators but work fine on real devices?
