### ISSUE TITLE
Padding does not work as expected

### ISSUE THREAD

**Issue by hhkkyy** [theyakka/qr.flutter#104]
```
import 'package:flutter/material.dart';
import 'package:qr_flutter/qr_flutter.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: Scaffold(
        appBar: AppBar(),
        body: Row(
          children: <Widget>[
            Expanded(child: QrImage(
              data: 'datadatadatadatadatadatadatadatadata',
              padding: EdgeInsets.zero,
            )),
            Expanded(child: QrImage(
              data: 'datadatadatadatadatadatadatadatadata',
              padding: EdgeInsets.all(5),
            )),
            Expanded(child: QrImage(
              data: 'datadatadatadatadatadatadatadatadata',
              padding: EdgeInsets.all(10),
            )),
            Expanded(child: QrImage(
              data: 'datadatadatadatadatadatadatadatadata',
              padding: EdgeInsets.all(15),
            )),
          ],
        ),
      ),
    );
  }
}
```
![image](https://user-images.githubusercontent.com/19389352/88788111-77649900-d1c7-11ea-8de0-64f32c15c5da.png)
![image](https://user-images.githubusercontent.com/19389352/88788083-703d8b00-d1c7-11ea-996b-a1f3ccd48a0a.png)

The 2nd qrCode and the 3rd one has different padding but share the 'same' size. I understand that they have different widget size and QrImage resized the image to the same. But this makes it impossible for me to get a qrCode with a size I wanted, it's always resized to some certain size. I think the image should always fit the size of the widget.

What's more, with zero padding, the qrCode overflows the boudary. 
In my app this code caused overflow
```
Container(
  width: 80,
  child: QrImage(
    data: 'datadatadatadatadatadatadatadatadata',
    padding: EdgeInsets.zero,
  ),
),
```

![image](https://user-images.githubusercontent.com/19389352/88788946-a3cce500-d1c8-11ea-8370-d09c2ef4f9fd.png)

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.18362.959], locale zh-CN)
 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[!] Android Studio (version 3.2)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[!] IntelliJ IDEA Ultimate Edition (version 2017.3)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code, 64-bit edition (version 1.41.0)
[√] Connected device (1 available

  qr_flutter: ^3.0.1

**Comment by hhkkyy** [comment]
I changed the following code in qr_painter.dart line 389 and the bug seems solved
```
  void _calculateMetrics() {
    final gapTotal = (moduleCount - 1) * gapSize;
    var pixelSize = (containerSize - gapTotal) / moduleCount;
    // _pixelSize = (pixelSize * 2).roundToDouble() / 2;
    _pixelSize = pixelSize;
    _innerContentSize = (_pixelSize * moduleCount) + gapTotal;
    _inset = (containerSize - _innerContentSize) / 2;
  }
```

Seems roundToDouble caused this, it makes every single square has an int size W and for the entire image it causes the image size only allowed in certain sizes that is n times of W. Hope this will help.

**Comment by Yann39** [comment]
I am also facing this bug and I can confirm the change suggested fixes the problem.

**Comment by tristansb1** [comment]
Yep, facing this bug here also.

**Comment by andyxiaoxi** [comment]
me too

**Comment by ximi66** [comment]
Is this bug still unresolved？

**Comment by vanlooverenkoen** [comment]
I used the sollution of @hhkkyy  and created a pull request #144

**Comment by vanlooverenkoen** [comment]
Use this for now
```
  qr_flutter:
    git:
      url: https://github.com/vanlooverenkoen/qr.flutter
      ref: bugfix/#104-padding-fix
```

**Comment by lukef** [comment]
Fixed in 5.0.0.

**Comment by Ben-Spotec** [comment]
@lukef It's still qr_flutter 4.0.0 in pub.dev and when publish 5.0.0？

**Comment by CaiWanFeng** [comment]
@lukef It's still qr_flutter 4.0.0 and when publish 5.0.0

**Comment by vanlooverenkoen** [comment]
It seems that 5.0.0 is 91% done. Only 1 web ticket. You can find the progress here for 5.0.0 (https://github.com/theyakka/qr.flutter/milestone/3) @lukef do you have a timeline when we can expect this version?
