### ISSUE TITLE
Non-fatal Exception: java.lang.Exception: QrInputTooLongException: Input too long. 28852 > 23648

### ISSUE THREAD

**Issue by kw2019ltd** [theyakka/qr.flutter#105]
hi,
can you increase limit? 

Non-fatal Exception: java.lang.Exception
QrInputTooLongException: Input too long. 28852 > 23648

**Comment by lukef** [comment]
The limit is imposed by the QR code standard and is not something I can raise. You could try a different mode, but the limits are fixed.
