### ISSUE TITLE
Failed assertion: boolean expression must not be null

### ISSUE THREAD

**Issue by WindWZQ** [theyakka/qr.flutter#108]
**Describe the bug**
error:Failed assertion: boolean expression must not be null. 
when i use the QrImage.withQr with QrCode.fromUint8List.

### Here's the code:
``` dart
  Widget _body(BuildContext context) {
    var list = Uint8List.fromList([1, 2, 3, 4, 5]);

    var parent = QrImage.withQr(
        qr: QrCode.fromUint8List(
            data: list, errorCorrectLevel: QrErrorCorrectLevel.L));

    return parent;
  }
```

### Hers's the error:
The following assertion was thrown during paint():
Failed assertion: boolean expression must not be null

The relevant error-causing widget was: 
  QrImage file:///C:/Users/wind/AndroidStudioProjects/flutter_demo/lib/ui/HomePage.dart:29:26
When the exception was thrown, this was the stack: 
1   QrPainter.paint (package:qr_flutter/src/qr_painter.dart:187:27)
2   RenderCustomPaint._paintWithPainter (package:flutter/src/rendering/custom_paint.dart:531:13)
3   RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:572:7)
4   RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2264:7)
5   PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
...
The following RenderObject was being processed when the exception was fired: RenderCustomPaint#d621d
...  parentData: offset=Offset(10.0, 10.0) (can use size)
...  constraints: BoxConstraints(w=340.0, h=340.0)
...  size: Size(340.0, 340.0)
RenderObject: RenderCustomPaint#d621d
  parentData: offset=Offset(10.0, 10.0) (can use size)
  constraints: BoxConstraints(w=340.0, h=340.0)
  size: Size(340.0, 340.0)

**Desktop (please complete the following information):**
 - OS: [android]
 - Version [29]

**Comment by liamappelbe** [comment]
I had the same issue. The fix is that you have to call `QrCode.make()` before you pass it to `QrImage.withQr`:

```
  Widget _body(BuildContext context) {
    var list = Uint8List.fromList([1, 2, 3, 4, 5]);

    var parent = QrImage.withQr(
        qr: QrCode.fromUint8List(
            data: list, errorCorrectLevel: QrErrorCorrectLevel.L)..make());

    return parent;
  }
```

I had to dig through the source code to figure this out. So it would be nice if there was an example of using the `QrImage.withQr` constructor in the readme.

**Comment by lukef** [comment]
`.make()` is now not required so this should be working as expected now.
