### ISSUE TITLE
QR image is not rendered after installation on device

### ISSUE THREAD

**Issue by hihassam** [theyakka/qr.flutter#109]
Hi I am having a wierd issue. I am using qr_flutter: ^3.2.0 for QR generation. Everything works ok during simulator testing in android studio as well as if i use connected device for testing but when i create an APK or install the app through playstore on android device the QR is not rendered. I only see a blank Grey screen. Please help.

**Comment by hihassam** [comment]
> Hi I am having a wierd issue. I am using qr_flutter: ^3.2.0 for QR generation. Everything works ok during simulator testing in android studio as well as if i use connected device for testing but when i create an APK or install the app through playstore on android device the QR is not rendered. I only see a blank Grey screen. Please help.

here is my code
 Expanded(
                  child:  Center(

                    child: RepaintBoundary(
                      key: globalKey,
                      child: QrImage(
                        data: 'test data',// _dataString,
                        size: 0.5 * bodyHeight,

                      ),
                    ),
                  ),
                ),

I am displaying this inside a Scaffold/CustomScrollView/Silverlist.
I am using version 3.1.0 of QR_FLUTTER Package. Even when i connect my cell phone as an emulator it works but when i convert the code to APK and then install it then it does not work.

**Comment by callmejm** [comment]
same , i got grey box also

**Comment by hihassam** [comment]
i resolved it my self. Use container instead of expanded.
