### ISSUE TITLE
Exporting QR code in *Flutter Web*

### ISSUE THREAD

**Issue by chapmacl** [theyakka/qr.flutter#110]
I'm trying to download the QR code but the PNG file is somehow corrupted or unreadable. This is the code I am using:

final image = await QrPainter(
        data: "data",
        version: QrVersions.auto,
        errorCorrectionLevel: QrErrorCorrectLevel.Q,
      ).toImage(500);
 final blob = html.Blob([image]);

final url = html.Url.createObjectUrlFromBlob(blob);

final anchor = html.document.createElement('a') as html.AnchorElement
        ..href = url
        ..style.display = 'none'
        ..download = 'qrcode.png';
html.document.body.children.add(anchor);
anchor.click();

**Comment by chapmacl** [comment]
And if I may request something:
For all of the times you have written "Please check previous issues", "I have already answered this", etc.
it would be much more helpful for future users of this plugin to simply update the README instead.
Thank you

**Comment by brenoasm** [comment]
@chapmacl I've managed to get it working doing something like this:

```
final embeddedImage = await _loadImage();

final image = await QrPainter(
  data: qrCode.url,
  version: QrVersions.auto,
  errorCorrectionLevel: QrErrorCorrectLevel.Q,
  embeddedImage: embeddedImage,
).toImageData(400);

var pngBytes = image.buffer.asUint8List();

return base64Encode(pngBytes);
```

Then the HTML part:

```
var download = document.createElement('a') as AnchorElement;

download.href = 'data:image/png;base64,<here goes the base64 image>';
download.download = 'qr_code.png';

download.click();

download.remove();
```

But my problem now is with the embedded image. I can't make it work in any way... Everytime I set the embedded image the downloaded image get corrupted (I'm using Flutter Web too).

**Comment by NicolaChimerapps** [comment]
@brenoasm this worked for me to download it as an image:
`final blob = Blob([image.buffer.asUint8List()], 'image/png');
final url = Url.createObjectUrlFromBlob(blob);
final anchor = document.createElement('a') as AnchorElement
                      ..href = url
                      ..style.display = 'none'
                      ..download = 'qr.png';
document.body.children.add(anchor);
anchor.click();
anchor.remove();`

**Comment by lukepighetti** [comment]
Closing because the community provided a solution and there is nothing actionable for us. Thank you all for the help.
