### ISSUE TITLE
[Question] What is the foregroundColor and backgroundColor for QrPainter? 

### ISSUE THREAD

**Issue by amadeu01** [theyakka/qr.flutter#112]
I'm using the `QrPainter` basically because I need the `ui.Image` to share the generated image with other apps. So, I'm not sure if I really must use that.

But, I saw that `emptyColor` is deprecated for `QrPainter` and it has the following comment:

> You should us the background color value of your container widget

That would be the `CustomPaint` widget? Anyway the `QrPainter` does not offer the `foregroundColor` and `backgroundColor` as the `QrImage`. What would be the proper setup of the colour with `QrPainter`?

**Comment by fbuireu** [comment]
The short answer is there isn't.

However, a workaround to export the `QrPainter` as image is to use the `QrDrawing` within a `GlobalKey` and create the raw image based on that key. Something like:

```
  Future<Uint8List> createImageFromRenderKey({GlobalKey<State<StatefulWidget>>? renderKey}) async {
    final RenderRepaintBoundary boundary = renderKey?.currentContext?.findRenderObject()! as RenderRepaintBoundary;

    if (boundary.debugNeedsPaint) {
      await Future.delayed(const Duration(milliseconds: 20));
      createImageFromRenderKey(renderKey: renderKey);
    }

    final ui.Image image = await boundary.toImage(pixelRatio: 3);
    final ByteData? byteData = await image.toByteData(format: ui.ImageByteFormat.png);

    return byteData!.buffer.asUint8List();
  }
```
`createImageFromRenderKey` is the method to be called on your "export" button created from:
``` 
   final GlobalKey globalKey = GlobalKey();
```

The `boundary.debugNeedsPaint` is a workaround to bypass Flutter's limitation from https://github.com/flutter/flutter/issues/22308 where the `RepaintBoundary` class may be being used when the UI is being rehydrated, causing an unhandled exception or creating a low-quality image. So if the UI is being painted at that time, I rethrow the method.

**Comment by lukef** [comment]
This will be totally changing in 5.0.
