### ISSUE TITLE
EmbeddedImage not centralized 

### ISSUE THREAD

**Issue by brenoasm** [theyakka/qr.flutter#122]
Hi, I'm running a full screen QRCode image in a web application, but the embedded image is not centralized (The camera image).

![image](https://user-images.githubusercontent.com/25211056/103566284-84856280-4ea0-11eb-9801-1afd4bad5319.png)

To reproduce it I just created a new project (Web) and set an embedded image inside a fullscreen Container widget.

```
Container(
      padding: EdgeInsets.all(30),
      height: MediaQuery.of(context).size.height,
      width: double.minPositive,
      child: QrImage(
        data: widget.data,
        embeddedImage:  'path_to_the_image',
      ),
)
```

Thanks in advance.

**Comment by lukef** [comment]
Fixed in 5.0.0
