### ISSUE TITLE
QrPainter - Add padding like QrImage

### ISSUE THREAD

**Issue by jeremy-giles** [theyakka/qr.flutter#126]
I created an application that allows to generate and save QRCodes.
I am using the QrImage widget to show the user the final result. For save the QRCode, I generate the latter with the QrPainter object like this :
```
ByteData qrBytes = await QrPainter(
      data: _encodedValue,
      gapless: true,
      version: QrVersions.auto,
      color: Color.fromRGBO(0, 0, 0, 1),
      emptyColor: Colors.white,
    ).toImageData(878);
```
But it isn't possible to add a padding to the generated image.

Sometimes some site / software display the QRCode with a black overlay. In this case it becomes difficult to scan the QRCode. A simple and efficient solution is to add a padding of a few pixels around the QRCode. Some barcode generator sites offer this option.

**Comment by svprdga** [comment]
This would be really helpful since as @jeremy-giles says, sometimes the generated image is hard to read.

**Comment by svprdga** [comment]
As a dirty workaround, I have created an additional painter that outputs the original image with a higher size, filling the borders with white color:

```
import 'package:flutter/material.dart';
import 'dart:ui' as ui;

import 'package:flutter/services.dart';

class CodePainter extends CustomPainter {

  // ********************************* VARS ******************************** //

  final double margin;
  final ui.Image qrImage;
  Paint _paint;

  // ***************************** CONSTRUCTORS **************************** //

  CodePainter({@required this.qrImage, this.margin = 10}) {
    _paint = Paint()
      ..color = Colors.white
      ..style = ui.PaintingStyle.fill;
  }

  //***************************** PUBLIC METHODS *************************** //

  @override
  void paint(Canvas canvas, Size size) {
    // Draw everything in white.
    final rect = Rect.fromPoints(Offset.zero, Offset(size.width, size.height));
    canvas.drawRect(rect, _paint);

    // Draw the image in the center.
    canvas.drawImage(qrImage, Offset(margin, margin), Paint());
  }

  @override
  bool shouldRepaint(covariant CustomPainter oldDelegate) => false;

  ui.Picture toPicture(double size) {
    final recorder = ui.PictureRecorder();
    final canvas = Canvas(recorder);
    paint(canvas, Size(size, size));
    return recorder.endRecording();
  }

  Future<ui.Image> toImage(double size,
      {ui.ImageByteFormat format = ui.ImageByteFormat.png}) async {
    return await toPicture(size).toImage(size.toInt(), size.toInt());
  }

  Future<ByteData> toImageData(double originalSize,
      {ui.ImageByteFormat format = ui.ImageByteFormat.png}) async {
    final image = await toImage(originalSize + margin * 2, format: format);
    return image.toByteData(format: format);
  }
}
```

Usage:

```
    ui.Image image = await QrPainter(
      data: codeContent,
      gapless: true,
      version: QrVersions.auto,
      color: Color.fromRGBO(0, 0, 0, 1),
      emptyColor: Colors.white,
    ).toImage(_SHARE_IMAGE_SIZE);

    ByteData data = await CodePainter(qrImage: image)
        .toImageData(_SHARE_IMAGE_SIZE);
```

**Comment by jeremy-giles** [comment]
Hey @svprdga, I also created a CustomPainter to add a background slightly larger than the QrCode.
```
class QrBackground extends CustomPainter {

  final ui.Image image;

  QrBackground({@required this.image});

  @override
  void paint(Canvas canvas, Size size) {
    final paint = Paint()
      ..isAntiAlias = true
      ..style = PaintingStyle.fill
      ..color = Colors.white;

    canvas.drawRRect(
      RRect.fromRectAndRadius(
          Rect.fromLTWH(0, 0, 500, 500), Radius.circular(20)),
      paint,
    );

    final imagePaint = Paint()
      ..isAntiAlias = true
      ..filterQuality = FilterQuality.high;
    final position = Offset(
      (size.width - image.width) / 2.0,
      (size.height - image.height) / 2.0,
    );
    canvas.drawImage(image, position, imagePaint);
  }
}
```

**Comment by braysonjohn148** [comment]
> As a dirty workaround, I have created an additional painter that outputs the original image with a higher size, filling the borders with white color:
> 
> ```
> import 'package:flutter/material.dart';
> import 'dart:ui' as ui;
> 
> import 'package:flutter/services.dart';
> 
> class CodePainter extends CustomPainter {
> 
>   // ********************************* VARS ******************************** //
> 
>   final double margin;
>   final ui.Image qrImage;
>   Paint _paint;
> 
>   // ***************************** CONSTRUCTORS **************************** //
> 
>   CodePainter({@required this.qrImage, this.margin = 10}) {
>     _paint = Paint()
>       ..color = Colors.white
>       ..style = ui.PaintingStyle.fill;
>   }
> 
>   //***************************** PUBLIC METHODS *************************** //
> 
>   @override
>   void paint(Canvas canvas, Size size) {
>     // Draw everything in white.
>     final rect = Rect.fromPoints(Offset.zero, Offset(size.width, size.height));
>     canvas.drawRect(rect, _paint);
> 
>     // Draw the image in the center.
>     canvas.drawImage(qrImage, Offset(margin, margin), Paint());
>   }
> 
>   @override
>   bool shouldRepaint(covariant CustomPainter oldDelegate) => false;
> 
>   ui.Picture toPicture(double size) {
>     final recorder = ui.PictureRecorder();
>     final canvas = Canvas(recorder);
>     paint(canvas, Size(size, size));
>     return recorder.endRecording();
>   }
> 
>   Future<ui.Image> toImage(double size,
>       {ui.ImageByteFormat format = ui.ImageByteFormat.png}) async {
>     return await toPicture(size).toImage(size.toInt(), size.toInt());
>   }
> 
>   Future<ByteData> toImageData(double originalSize,
>       {ui.ImageByteFormat format = ui.ImageByteFormat.png}) async {
>     final image = await toImage(originalSize + margin * 2, format: format);
>     return image.toByteData(format: format);
>   }
> }
> ```
> 
> Usage:
> 
> ```
>     ui.Image image = await QrPainter(
>       data: codeContent,
>       gapless: true,
>       version: QrVersions.auto,
>       color: Color.fromRGBO(0, 0, 0, 1),
>       emptyColor: Colors.white,
>     ).toImage(_SHARE_IMAGE_SIZE);
> 
>     ByteData data = await CodePainter(qrImage: image)
>         .toImageData(_SHARE_IMAGE_SIZE);
> ```

Works perfectly. Made my client pay ealier.

**Comment by lukef** [comment]
In 5.0.0 you should be able to add an `inset` to the painter directly.

![image](https://user-images.githubusercontent.com/37941/156840698-c14e3548-3758-4c51-9012-cb54b600a7b2.png)
