### ISSUE TITLE
Migrating to null safety

### ISSUE THREAD

**Issue by bananagag** [theyakka/qr.flutter#127]
Since the packages this package depended on are all ready for null safety now, it's time for qr.flutter to also start migrating to null safety.

**Comment by IchordeDionysos** [comment]
@lukef Would appreciate if support for null safety would be coming 👍 

The Dart/Flutter team already encourages publishing the migrated packages: See [this blog post](https://medium.com/dartlang/preparing-the-dart-and-flutter-ecosystem-for-null-safety-e550ce72c010).

**Comment by nilsreichardt** [comment]
@lukef There is also a video tutorial: [How to migrate Dart packages to null safety](https://youtu.be/eBr5tlumwlg)

**Comment by IchordeDionysos** [comment]
The new Dart version with null-safety was just released 😍 
https://medium.com/dartlang/announcing-dart-2-12-499a6e689c87

**Comment by vishnuagbly** [comment]
when will null safety be added?

**Comment by fzyzcjy** [comment]
+1 looking forward to the update

**Comment by jonas-zebari** [comment]
Is help needed in migrating to NNBD? This is my final dependency that hasn't migrated and I am more than willing to help. I just don't want to duplicate work someone else may be doing already :)

**Comment by lukef** [comment]
I'm not planning to do it immediately. If you have time feel free to submit a PR.

**Comment by fzyzcjy** [comment]
@lukef I will submit a pr soon

**Comment by fzyzcjy** [comment]
@lukef PR created https://github.com/theyakka/qr.flutter/pull/129

**Comment by nilsreichardt** [comment]
There are now 2 PRs: #129 & #128

**Comment by kw2019ltd** [comment]
> 
> 
> I'm not planning to do it immediately. If you have time feel free to submit a PR.

PR submitted can you review it

**Comment by lailai0715** [comment]
Looking forward to getting null-safety support for this package

**Comment by ErliSoares** [comment]
Any estimates?

**Comment by vishnuagbly** [comment]
> Any estimates?

PR #129 has already been opened, we are waiting for it to merge.

**Comment by lukepighetti** [comment]
I'm going to see if I can get this across the finish line.

**Comment by lukepighetti** [comment]
resolved by https://github.com/theyakka/qr.flutter/pull/130
