### ISSUE TITLE
Handling permission denied to access the camera

### ISSUE THREAD

**Issue by wahyu-handayani** [theyakka/qr.flutter#135]
I am using the latest version of qr_flutter:4.0.0 and doing test in simulator, so when I start to hit the button to scan the qr code, I always get
```
Exception has occurred.
CameraException (CameraException(cameraPermission, Permission denied to access the camera))
```
I have added this in info.plist:
```
<key>NSCameraUsageDescription</key>
<string>This app requires read and write permission from user</string>
```
I had been trying to use a package that relate for using camera permission (image picker), so when I use image picker package, starting by clicking the button to start camera then pop up dialog shows to ask permission to access camera and when I press to allow access, another pop up shows that say ```camera not available``` cause I am using simulator. So, instead of getting error exception for Permission denied to access the camera, is there a way to get pop up to ask permission access for camera? I also have checked the status permission to access camera and it says permission is granted

**Comment by lukepighetti** [comment]
iOS simulator does not support camera use.

**Comment by wahyu-handayani** [comment]
I am so sorry @lukepighetti I am doing mistake, I just realise that I am using another package and posting the issue in the wrong place, thank you for closing this issue
