### ISSUE TITLE
add support for pretty qr code 

### ISSUE THREAD

**Issue by kw2019ltd** [theyakka/qr.flutter#136]
hi
its possible to impalement/enhance current qr code widget to support pretty qr code

where icon in middle of qr code

![image](https://user-images.githubusercontent.com/47334522/114179663-f1007980-9947-11eb-8bcc-c4f675175173.png)

![image](https://user-images.githubusercontent.com/47334522/114179690-f8278780-9947-11eb-8ed4-fa89f50fa687.png)

**Comment by ronytesler** [comment]
Isn't it 'embeddedImage'?

**Comment by caseyryan** [comment]
> Isn't it 'embeddedImage'?

it's not. Currently the image is only drawn over the QR and if it's too large the QR won't be readable

**Comment by lukef** [comment]
5.0 will support the exclusion of the pixels behind the image. However, you need to use _sensible_ image sizes and data quality / error check values. If you don't the code will **not** be readable.
