### ISSUE TITLE
Qr 'shifting' on ExpansionTile

### ISSUE THREAD

**Issue by antojqp** [theyakka/qr.flutter#139]
I've got no idea why but upon testing my app on this part

`ExpansionTile(
 initiallyExpanded: open,
title: Text(title),
subtitle: Text(subTitle),
leading: Icon(icon),
children: [
QrImage(
data: 11111,
errorCorrectionLevel: QrErrorCorrectLevel.H,
version: QrVersions.auto,
),
Text(
code,
),
],
),
`

The qr code that is generated upon closing the tile it 'shifts' I'll attach a photo of what's happening
![Screenshot from 2021-05-31 14-59-41](https://user-images.githubusercontent.com/38183841/120228170-f8921f80-c220-11eb-9323-0b18bbe3a615.png)

my guess is that it has something to do with the expansion tile (since on its own it works fine) please help

**Comment by lukef** [comment]
Can't reproduce in 5.0. Might be fixed.

**Comment by AdrienLemaire** [comment]
I see that my issue #194 is the same as this one. Any idea when 5.0 might be released @lukef ?
