### ISSUE TITLE
New option for url, embedded widget.

### ISSUE THREAD

**Issue by ibhanu** [theyakka/qr.flutter#140]
**Is your feature request related to a problem? Please describe.*

Feature 1:
- options for url, because qr scanner takes data as text only which sometimes get scanned as text and doesn't redirect to desired url.

Feature 2:
- option to add embedded widget. If we use widget in between the qr code it will be easier add infinite number of combination like icons, LottieAnimation, for me I don't want NetworkImage. But rather diff widget to handle my network handle which will show loader while the image is loading. But right now. QR is generated only when the images is loaded because we it need imageProvider.

**Comment by jpSimkins** [comment]
I really need to embed Text but it doesn't support it. Luckily, I am able to do this when printing. The client is annoyed that what is printed is not shown in the QR when they look at it, so for now... at least printing can allow this.

**Comment by lukef** [comment]
re: url. The QR code standard supports fixed data types. It's the job of the scanner software to differentiate them. If you need something custom you will need to define your own protocol. e.g.: myapp://go/to/here or something like that. If a url is being recognized as text, this is the issue with the scanner.

re: embedding widgets. I can take a look.
