### ISSUE TITLE
My QR Code cannot be read if i embedded a logo

### ISSUE THREAD

**Issue by linxkaa** [theyakka/qr.flutter#142]
**Describe the bug**
Scanner didnt read my qr code that i generate with embedded image, if i remove the embedded image there will be no issues. But i have to make this logo inside the QR code

**Expected behavior**
I want to make a logo inside the QR code

**Screenshots**
<img width="194" alt="Screen Shot 2021-07-29 at 15 42 16" src="https://user-images.githubusercontent.com/57997512/127461073-8bcea348-6940-41f8-83ff-2fa7df1fcaf0.png">
<img width="605" alt="Screen Shot 2021-07-29 at 15 46 17" src="https://user-images.githubusercontent.com/57997512/127461487-f646601c-28a2-4d3e-ba41-f5454f92742a.png">

**Smartphone (please complete the following information):**
 - Device: Samsung A21 
 - OS: 10

**Additional context**
this was my code in my Flutter Application
```
QrImage(
              embeddedImage: AssetImage('assets/images/logo_mlm.png'),
              gapless: false,
              data: "https://md.palunaga.my.id/r/MEMBERID",
              version: QrVersions.auto,
              embeddedImageStyle: QrEmbeddedImageStyle(
                size: Size(40, 40),
              ),
              size: UIHelper.setSp(400),
            )
```

**Comment by ahd-webtest** [comment]
**Any update?**

**Comment by HugoSart** [comment]
I also need this

**Comment by eli1stark** [comment]
It happens because the image just covers a part of QRCode, what it needs to do is to just draw QRCode around the image, I don't know if this is possible to do in the current implementation of the package

**Comment by nerder** [comment]
@eli1stark not really, is just a matter of "density" probably. A more dense QR code can be detected even with an image that covers the central part of it.

**Comment by eli1stark** [comment]
I didn't know that a QR code can function without some part of it. I am genuinely curious right how QR codes work under the hood. By the way, the high density really solves the problem, at least for me

**Comment by kaundi** [comment]
The embedded logo should be less than 30% of the size of the QR code. and also add `errorCorrectionLevel: QrErrorCorrectLevel.H,`

My code:
`QrImage(
                                      version: QrVersions.auto,
                                      errorCorrectionLevel: QrErrorCorrectLevel.H,
                                      embeddedImageStyle: QrEmbeddedImageStyle(
                                        size: Size(40, 40),
                                      ),
                                      data: ''https://google.com',
                                      size: 160.0,
                                      embeddedImage: AssetImage(
                                          "assets/images/marker.png"),
                                    ),`

**Comment by leeyisoft** [comment]
> The advice given seems good and this isn't something that can be "fixed" in the core code. It's about using sensible values.

It would be nice to be able to add a raised border to embeddedImage, or to customize other styles

**Comment by leeyisoft** [comment]
我也想在二维码里面做一个logo，并且期望logo是圆形的白色边框凸起的

I also want to make a logo inside the QR code, and I expect the logo to be round with white frame raised

**Comment by kemalturk03** [comment]
> 

this worked for me

**Comment by alijonxr** [comment]
> 

works
