### ISSUE TITLE
Unable to scan qr image if foreground color is white

### ISSUE THREAD

**Issue by calebdeji** [theyakka/qr.flutter#145]
`QrImage(
       data: address.address,
       size: 200,
       foregroundColor: Colors.white,
)`

Qr scanner doesn't read any data from the image whenever the foreground color is set to white

**Comment by lukef** [comment]
`foregroundColor` is deprecated. Are you rendering this on a dark background? I don't think this has anything to do with the library. Probably the scanning method.
