### ISSUE TITLE
unable to make QrImage from QrCode build with QrCode.fromUint8List() constructor

### ISSUE THREAD

**Issue by DanielMayr** [theyakka/qr.flutter#149]
minimal example:
QrImage.withQr(
   qr: QrCode.fromUint8List(data: Uint8List(12),
                                             errorCorrectLevel: QrErrorCorrectLevel.M),
   version: QrVersions.auto,
)

error message: 
"null check was used on a null value"

quick fix:
encode Uint8List with base64 and provide data as String.

**Comment by robin2005** [comment]
var qr = QrCode.fromUint8List(data: Uint8List(12)；
qr.make()

**Comment by lukef** [comment]
`.make()` has been removed so this should be functioning as expected now.
