### ISSUE TITLE
unable to paint the qr code

### ISSUE THREAD

**Issue by Mike-3** [theyakka/qr.flutter#150]
i have the exception Unhandled Exception: Null check operator used on a null value
the values fom _modules are all null => check isDark -> exception

`  var qrCode = qr.QrCode.fromData(
    data: code,
    errorCorrectLevel: qr.QrErrorCorrectLevel.L,
  );
  var bytes = await qr.QrPainter.withQr(
    qr: qrCode,
    emptyColor:COLOR_QR_BACKGROUND,
    gapless: true,
  ).toImageData(qrCode.moduleCount * 5.0 + 10);`

**Comment by iandis** [comment]
This occurs to me too, I think we need to stick to using `QrPainter` instead of `QrPainter.withQr` for now.

**Comment by lukef** [comment]
I think this issue stemmed from not calling `qrCode.make()` which is now not required.
