### ISSUE TITLE
Dependency issues

### ISSUE THREAD

**Issue by lehnen** [theyakka/qr.flutter#160]
Hey,

my project depends on qr ^3.0.0 and qr_flutter >=4.0.0 depends on qr ^2.0.0.
Is it possible to upgrade your dependencies?

Thx,
Volker

**Comment by jefrisingh** [comment]
I can't use qr_flutter with qr:3.0.0 since both project exports QrImage and the class is miss matched everyware making the project failed to compile

**Comment by insinfo** [comment]
remove re-export of lib qr from qr.flutter

**Comment by jpSimkins** [comment]
I've ran into this same issue with trying to print the QR code using [printing](https://pub.dev/packages/printing).

Seems there is a [PR](https://github.com/theyakka/qr.flutter/pull/165) made to resolve this issue. Please merge.
