### ISSUE TITLE
upgrade to qr 3.0.0 to work with pdf: ^3.6.5

### ISSUE THREAD

**Issue by insinfo** [theyakka/qr.flutter#161]
upgrade to qr 3.0.0 to work with pdf: ^3.6.5

**Comment by ciamax** [comment]
Same issue here

**Comment by insinfo** [comment]
@ciamax 
I made a fork that fixes this issue, maybe it will help you while we wait for @theyakka to update this package with this solution.

https://github.com/insinfo/qr.flutter

**Comment by ciamax** [comment]
> @ciamax I made a fork that fixes this issue, maybe it will help you while we wait for @theyakka to update this package with this solution.
> 
> https://github.com/insinfo/qr.flutter

Hello and thank you for the workaround. I have made some test and it seems to work

**Comment by lukef** [comment]
It's being worked on
