### ISSUE TITLE
 Can I Download QR Image or  shard QR

### ISSUE THREAD

**Issue by MahmedRahman** [theyakka/qr.flutter#162]
Download QR Image 
shard QR

https://medium.com/codex/exporting-qr-codes-in-flutter-dd30220fcba4

**Comment by lukef** [comment]
Great article. Thanks.

**Comment by MOhsain** [comment]
Can anyone please paste solution here from this article, because i have not my upgraded account :(

**Comment by nicolasvahidzein** [comment]
Can someone paste the code here please, i don't have access to medium.
