### ISSUE TITLE
Please Update this package cause qr ^3.0.0 not compatible

### ISSUE THREAD

**Issue by abdulrehmananwar** [theyakka/qr.flutter#166]
Please Update this package cause qr ^3.0.0 not compatible.

**Comment by lukef** [comment]
It's happening. Will have a 5.0 soon.

**Comment by mikeesouth** [comment]
@lukef Sorry for bumping a closed thread but when is soon? It's becoming a real blocker for me and I prefer to not use dependency overrides. Great package btw!
