### ISSUE TITLE
Need a larger white background for export to png

### ISSUE THREAD

**Issue by DarenF-20C** [theyakka/qr.flutter#201]
I try to export the QrPainter.withQr(), but it cannot be scan by QR scanner. Because it does not have something like white border or background of other colour in some app.
I wish to repaint the qr or add white background with larger size before export (toimagedata).

    final painter = QrPainter.withQr(
      qr: invitationQr,
      color: const Color(0xFF000000),
      gapless: true,
      embeddedImageStyle: null,
    );

    final picData = await painter.toImageData(2048);
    await writeToFile(picData!, path);

There's no border corner that google lens can recognise.
![Screenshot_20230203_182209](https://user-images.githubusercontent.com/80732760/216577010-9146b29b-941c-4838-984c-8914bf9ac11c.jpg)

**Comment by BraveEvidence** [comment]
This might help https://www.youtube.com/watch?v=9ADSWmPCJMg&list=PLQhQEGkwKZUqZC2QAp_u4ZAzqpsCCRvmM&index=6 https://www.youtube.com/watch?v=ZRUE1i15TYw&list=PLQhQEGkwKZUqZC2QAp_u4ZAzqpsCCRvmM&index=7

**Comment by DarenF-20C** [comment]
I solved by doing like this.

1. Before writeToFile, I get the Qr to ImageData (.toImage(2048))

`  final picData = await painter.toImage(2048);
    dynamic qrPainted = await QrCodePainter(qrImage: picData, margin: 30).toImageData(2048);
    await writeToFile(qrPainted!, path);
`

And pass the picData to QrCodePainter

2. Then, QrCodePainter is here, just pasted it below.

`class QrCodePainter extends CustomPainter {
  final double margin;
  final ui.Image qrImage;
  late Paint _paint;

  QrCodePainter({required this.qrImage, this.margin = 10}) {
    _paint = Paint()
      ..color = Colors.white
      ..style = ui.PaintingStyle.fill;
  }

  @override
  void paint(Canvas canvas, Size size) {
    // Draw everything in white.
    final rect = Rect.fromPoints(Offset.zero, Offset(size.width, size.height));
    canvas.drawRect(rect, _paint);

    // Draw the image in the center.
    canvas.drawImage(qrImage, Offset(margin, margin), Paint());
  }

  @override
  bool shouldRepaint(covariant CustomPainter oldDelegate) => false;

  ui.Picture toPicture(double size) {
    final recorder = ui.PictureRecorder();
    final canvas = Canvas(recorder);
    paint(canvas, Size(size, size));
    return recorder.endRecording();
  }

  Future<ui.Image> toImage(double size,
      {ui.ImageByteFormat format = ui.ImageByteFormat.png}) async {
    return await toPicture(size).toImage(size.toInt(), size.toInt());
  }

  Future<ByteData?> toImageData(double originalSize,
      {ui.ImageByteFormat format = ui.ImageByteFormat.png}) async {
    final image = await toImage(originalSize + margin * 2, format: format);
    return image.toByteData(format: format);
  }
}
`

3. Then get the return value and write it to file. refers step 1 code.

**Comment by DarenF-20C** [comment]
This is how it looks like, after paint.

<img src="https://user-images.githubusercontent.com/80732760/225827605-89dc14d7-fa55-4fc1-9d23-aeee847ac972.png" width="256">
