### ISSUE TITLE
Bump major version when breaking changes are introduced

### ISSUE THREAD

**Issue by vbuberen** [theyakka/qr.flutter#205]
This is not a bug report, but a request for future to not introduce breaking changes without changing the major version as it breaks projects for lots of people. Changes introduced in `4.0.1 `with class renaming had to be a bump to `5.0.0`

Please read https://semver.org/ and use it for future releases.

**Comment by lukef** [comment]
Yes. I realised after publishing that there were breaking changes. I'm prepping a 5.0 release too, but unfortunately I can't unroll the dice here. Thanks for the report though.
