### ISSUE TITLE
InputTooLongException (QrInputTooLongException: Input too long. 1247860 > 10208)

### ISSUE THREAD

**Issue by kylequang** [theyakka/qr.flutter#211]
I pass base64Image via QR code but I have error 

![image](https://github.com/theyakka/qr.flutter/assets/67398186/1053f19b-be12-4797-bd06-c212e50a2cce)

How can i fix it (base64 or Uint8list)

**Comment by lukef** [comment]
You will need to increase the QR version number or reduce error checking. QR codes don't have an unlimited amount of data storage.
