### ISSUE TITLE
support of alphanumeric coding

### ISSUE THREAD

**Issue by stefano2012** [theyakka/qr.flutter#87]
Hi, 

I would strongly recommend to add alphanumeric suppert. Often (as in my case) only a url is coded with standard chars. Using alphanumeric coding the QR code image gets smaller which makes it easier to place it and can be bigger which is better for readability.

Let me know what you think about it...

best,
Stefano

**Comment by lukef** [comment]
This is a great idea but it should probably happen in the parent library (https://github.com/kevmoo/qr.dart). I'll look at logging a bug or doing a PR there.

**Comment by stefano2012** [comment]
Hi Luke,

you are right! In the meantime I found that out as well and I put a request there already. When it is implemented we may have to make a small extension to the Interface as well. In total I am sure it is not much effort since it is only an additional coding table for the alphanumeric support.

Stefano

On 23. Jun 2020, at 00:18, Luke <notifications@github.com> wrote:

﻿
This is a great idea but it should probably happen in the parent library (https://github.com/kevmoo/qr.dart). I'll look at logging a bug or doing a PR there.

**Comment by lukef** [comment]
Looks like this was solved upstream so closing!
